# Session Cookie
server.servlet.session.cookie.secure=true
app.time.fixed-instant=

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# SQL Init
spring.sql.init.mode=never
